### ISSUE TITLE
Docker-compose.yml: mapping key "." already defined

### ISSUE THREAD

**Issue by wetneb** [etalab/transport-site#4637]
Quand je lance `docker-compose up` comme documenté dans le README.md, j'obtiens:
```
$ docker-compose up
yaml: unmarshal errors:
  line 32: mapping key "." already defined at line 30
  line 34: mapping key "." already defined at line 30
  line 34: mapping key "." already defined at line 32
```

Il semble effectivement y avoir un problème d'indentation dans `docker-compose.yml`:
```yml
volumes:
  pgdata:
  .:
  build:
  .:
  deps:
  .:
```
